
## SPODS--Simple Physics Object based Detector Simulation
## Copyright (C) 2011, 2012, 2013 Justin Hugon

maxEvents: 1000000
keepGenParticles: true
keepNonFinalStateGenParticles: false

maxElectrons: 10
maxMuons: 10
maxPhotons: 10
maxJets: 10

etaElectronMax: 2.5
etaMuonMax: 2.4
etaPhotonMax: 2.5
etaJetMax: 5.0
etaMetMax: 5.0

ptElectronMin: 10.0
ptMuonMin: 10.0
ptPhotonMin: 10.0
ptJetMin: 10.0

# jet algorithm must be kt, ca, or antikt
jetAlg: antikt
jetAlgR: 0.5
jetVetoNPartMin: 2
jetVetoNChargMin: 1
jetVetoNHadMin: 1

## Isolation
## Type is either trk, calo, or comb
muonIsoType: trk
muonIsoConeSize: 0.2
muonIsoMinPt: 0.5

electronIsoType: trk
electronIsoConeSize: 0.3
electronIsoMinPt: 1.5

photonIsoType: trk
photonIsoConeSize: 0.3
photonIsoMinPt: 1.5

# b-tag
bTagEff: 0.8
bTagMistagRate: 0.1

## Skimming Config:
# All minX, metMin, htMin combined with Logical AND

skim:
  minPO: 0          #Min nElectrons + nMuons + nJets + nPhotons
  minLeptons: 0     #Min nElectrons + nMuons
  minMuons: 0
  minElectrons: 0
  minPhotons: 0
  minJets: 0

  #Above Minimum Numbers Must Pass below Pt Cuts (after normal pt/eta cuts)
  ptElectronMin: 20.0
  ptMuonMin: 20.0
  ptPhotonMin: 30.0
  ptJetMin: 30.0

  metMin: 0.0
  htMin: 0.0        #Also relies on ptJetMin

# Pileup Configuration
pileupN: 20
pileupType: poisson
# pileupType can be poisson, flat (from 0 to pileupN), 
# or pileupN (All with exactly pileupN--pileupN must be int)

# This is fastjet jet area pileup subtraction
# See fastjet.fr for more info
# true do run subtraction, false to not run
jetBakOn: true
# jet algorithm must be kt, ca, or antikt
jetBakAlg: kt   # antikt is probably a bad choice
jetBakAlgR: 0.6 # Should be 0.4 to 0.6; 0.4 for busy events
# jet area type for background subtraction
# choices are active_area, active_area_explicit_ghosts, 
#            passive_area, one_ghost_passive_area
jetBakAreaType: active_area_explicit_ghosts

###################################################
#### No-Smearing Detector Parameterization ########
###################################################

#Muon Resolution
muonResEtaRanges:
 - [0,2.4] #Barrel

muonResConstTerm:
 - 0.00 #Barrel

#For Momentum in TeV
muonResSqrtTerm:
 - 0.0 #Barrel
 - 0.0 #Endcap

muonResHighPtCut:
 - 0.0 #Barrel

muonResHighPtConstTerm:
 - 0.00 #Barrel

#For Momentum in TeV
muonResHighPtSqrtTerm:
 - 0.0 #Barrel
 - 0.0 #Endcap

#Photon Resolution
photonResEtaRanges:
 - [0,3.0] #Barrel

photonResConstTerm:
 - 0.0 #Barrel

photonResOneOverETerm:
 - 0.0 #Barrel

photonResOneOverSqrtETerm:
 - 0.0 #Barrel

#Electron Resolution
#Electrons are Treated Identically to Photons, except:
# Below this ET Cut
electronResPtCut: 20.0

#This Resolution is Applied
electronResConstantTerm: 0.00

#Jet Resolution

# Jets below this pt won't be smeared
jetResPtCut:
 - 30.0

jetResEtaRanges:
 - [0,5.0] #Barrel

jetResConstTerm:
 - 0.0 #Barrel

jetResOneOverETerm:
 - 0.0 #Barrel

jetResOneOverSqrtETerm:
 - 0.0 #Barrel

